import type { MetadataRoute } from "next"

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.innotech-sys.com"

/** All public routes for the sitemap (excluding dynamic/private). */
const routes: string[] = [
  "",
  "/about",
  "/accessibility",
  "/case-studies",
  "/company",
  "/company/board-advisors",
  "/company/careers",
  "/company/careers/open-roles",
  "/company/investors",
  "/company/our-story",
  "/company/partners",
  "/company/team",
  "/company/values",
  "/contact",
  "/demo",
  "/industries",
  "/industries/airport-shopping-mall",
  "/industries/automated-depot",
  "/industries/autonomous-fleets",
  "/industries/autonomous-fleets/charge-depot",
  "/industries/logistics",
  "/industries/military",
  "/industries/mining",
  "/industries/port",
  "/legal/cookie-policy",
  "/legal/privacy-policy",
  "/legal/terms",
  "/products",
  "/products/autolock",
  "/products/autolock/access-control",
  "/products/autolock/autonomous-charging",
  "/products/autolock/fleet-orchestration",
  "/products/autolock/process-automation",
  "/products/radar-link",
  "/products/radar-link/drone-tracking",
  "/products/radar-link/micro-localization",
  "/products/radar-link/real-time-analytics",
  "/products/radar-link/v2x-communication",
  "/products/safeguard",
  "/products/safeguard/compliance-monitoring",
  "/products/safeguard/predictive-maintenance",
  "/products/safeguard/real-time-alerting",
  "/products/safeguard/threat-detection",
  "/resources",
  "/resources/blog",
  "/resources/case-studies",
  "/resources/docs",
  "/resources/faq",
  "/resources/playbooks",
  "/resources/videos",
  "/resources/whitepapers",
  "/solutions",
  "/solutions/charging-autonomous-vehicles",
  "/solutions/charging-heavy-duty",
  "/solutions/charging-mar",
  "/solutions/connectivity-v2i",
  "/solutions/connectivity-v2v",
  "/solutions/drone-tracking",
  "/solutions/micro-localization",
  "/solutions/safety-human-robot",
  "/solutions/safety-industrial-robots",
  "/solutions/safety-mar",
  "/technology",
]

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((path) => ({
    url: `${baseUrl}${path || "/"}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: path === "" ? 1 : path.split("/").length <= 2 ? 0.9 : 0.7,
  }))
}
